CREATE DATABASE PRJ302_MusicStremingDB;
GO

USE PRJ302_MusicStremingDB;
GO

CREATE TABLE ROLES(
	roleID INT IDENTITY(1,1) PRIMARY KEY,
	roleName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USERS(
	userID INT IDENTITY(1,1) PRIMARY KEY,
	userName VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(100) UNIQUE,
	password VARCHAR(255) NOT NULL,
	avatar VARCHAR(255),
	fullName VARCHAR(100),
	birthday DATE,
	gender VARCHAR(10),
	createDate DATETIME NOT NULL DEFAULT GETDATE(),
	lastLogin DATETIME,
	[status] TINYINT NOT NULL DEFAULT 1,
	roleID INT NOT NULL,
	CONSTRAINT FK_User_Role
	FOREIGN KEY(roleID) REFERENCES ROLES(roleID)
);

CREATE TABLE ARTIST(
	artistID INT IDENTITY(1,1) PRIMARY KEY,
	artistName VARCHAR(100) NOT NULL,
	avatarURL VARCHAR(255),
	[description] NVARCHAR(MAX),
	debutDate DATE,
	isActive TINYINT NOT NULL DEFAULT 1
)

CREATE TABLE ALBUM(
	albumID INT IDENTITY(1,1) PRIMARY KEY,
	albumName VARCHAR(200) NOT NULL,
	coverImage VARCHAR(255),
	releaseDate DATE,
	isActive TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE SONG(
	songID INT IDENTITY(1,1) PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	duration INT NOT NULL,
	audioURL VARCHAR(255) NOT NULL,
	lyric NVARCHAR(MAX),
	releaseDate DATE,
	coverImage VARCHAR(255),
	isActive TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE SONG_ARTIST(
	songID INT NOT NULL,
	artistID INT NOT NULL,
	CONSTRAINT PK_SongArtist PRIMARY KEY(songID, artistID),
	CONSTRAINT FK_SongArtist_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID),
	CONSTRAINT FK_SongArtist_Artist
	FOREIGN KEY(artistID) REFERENCES ARTIST(artistID)
);
CREATE TABLE ALBUM_ARTIST(
	albumID INT NOT NULL,
	artistID INT NOT NULL,
	CONSTRAINT PK_AlbumArtist PRIMARY KEY (albumID, artistID),
	CONSTRAINT FK_AlbumArtist_Album
	FOREIGN KEY(albumID) REFERENCES ALBUM(albumID),
	CONSTRAINT FK_AlbumArtist_Artist
	FOREIGN KEY(artistID) REFERENCES ARTIST(artistID)
);

CREATE TABLE ALBUM_SONG(
	albumID INT NOT NULL,
	songID INT NOT NULL,
	CONSTRAINT PK_AlbumSong PRIMARY KEY(albumID, songID),
	CONSTRAINT FK_AlbumSong_Album
	FOREIGN KEY(albumID) REFERENCES ALBUM(albumID),
	CONSTRAINT FK_AlbumSong_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE PLAYLIST(
	playListID INT IDENTITY(1,1) PRIMARY KEY,
	playListName VARCHAR(100) NOT NULL,
	userID INT NOT NULL,
	isPublic TINYINT NOT NULL DEFAULT 1,
	createDate DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_PlayList_User
	FOREIGN KEY(userID) REFERENCES USERS(userID)
);

CREATE TABLE PLAYLIST_SONG(
	playListID INT NOT NULL,
	songID INT NOT NULL,
	addDate DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_PlayListSong PRIMARY KEY(playListID, songID),
	CONSTRAINT FK_PlayListSong_PlayList
	FOREIGN KEY(playListID) REFERENCES PLAYLIST(playListID),
	CONSTRAINT FK_PlayListSong_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE FAVORITE_SONG(
	userID INT NOT NULL,
	songID INT NOT NULL,

	CONSTRAINT PK_FavoriteSong PRIMARY KEY(userID, songID),
	CONSTRAINT FK_FavoriteSong_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_FavoriteSong_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE LISTENING_HISTORY(
	userID INT NOT NULL,
	songID INT NOT NULL,
	listenedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_Listening_History PRIMARY KEY(userID, songID, listenedAt),
	CONSTRAINT FK_Listening_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_Listening_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE SONG_SHARE(
	userID INT NOT NULL,
	songID INT NOT NULL,
	shareAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_SongShare PRIMARY KEY(userID, songID, shareAt),
	CONSTRAINT FK_SongShare_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_SongShare_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE ARTIST_FOLLOW(
	userID INT NOT NULL,
	artistID INT NOT NULL,

	CONSTRAINT PK_ArtistFollow PRIMARY KEY(userID, artistID),
	CONSTRAINT FK_ArtistFollow_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_ArtistFollow_Artist
	FOREIGN KEY(artistID) REFERENCES ARTIST(artistID)
);

CREATE TABLE COMMENTS(
	commentID INT IDENTITY(1,1) PRIMARY KEY,
	userID INT NOT NULL,
	songID INT NOT NULL,
	content NVARCHAR(MAX) NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT GETDATE(),
	[status] TINYINT NOT NULL DEFAULT 1,

	CONSTRAINT FK_Comment_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_Comment_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE DONATION(
	donationID INT IDENTITY(1,1) PRIMARY KEY,
	userID INT NOT NULL,
	amount DECIMAL(10,2) NOT NULL,
	[message] VARCHAR(255),
	paymentMethod VARCHAR(50),
	[status] VARCHAR(20),
	createAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Donation_User
	FOREIGN KEY(userID) REFERENCES USERS(userID)
);

CREATE TABLE NOTIFICATIONS(
	notificationID INT IDENTITY(1,1) PRIMARY KEY,
	userID INT NOT NULL,
	title VARCHAR(100) NOT NULL,
	content VARCHAR(255),
	type VARCHAR(50),
	isRead TINYINT NOT NULL DEFAULT 0,
	createAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Notification_User
	FOREIGN KEY(userID) REFERENCES USERS(userID)
);

CREATE TABLE EMAIL_LOG(
	emailLogID INT IDENTITY(1,1) PRIMARY KEY,
	userID INT NOT NULL,
	email VARCHAR(100) NOT NULL,
	[type] VARCHAR(50),
	[status] VARCHAR(20),
	sentAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_EmailLog_User
	FOREIGN KEY(userID) REFERENCES USERS(userID)
);