CREATE DATABASE PRJ302_MusicStremingDB;
GO

USE PRJ302_MusicStremingDB;
GO

CREATE TABLE ROLES(
	roleID INT IDENTITY(1,1) PRIMARY KEY,
	roleName NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE USERS(
	userID INT IDENTITY(1,1) PRIMARY KEY,
	userName NVARCHAR(50) NOT NULL UNIQUE,
	email NVARCHAR(100) UNIQUE,
	password NVARCHAR(255) NOT NULL,
	avatar NVARCHAR(255),
	fullName NVARCHAR(100),
	birthday DATE,
	gender NVARCHAR(10),
	createDate DATETIME NOT NULL DEFAULT GETDATE(),
	lastLogin DATETIME,
	[status] TINYINT NOT NULL DEFAULT 1,
	roleID INT NOT NULL,
	CONSTRAINT FK_User_Role
	FOREIGN KEY(roleID) REFERENCES ROLES(roleID)
);

CREATE TABLE ARTIST(
	artistID INT IDENTITY(1,1) PRIMARY KEY,
	artistName NVARCHAR(100) NOT NULL,
	avatarURL NVARCHAR(255),
	[description] NVARCHAR(MAX),
	debutDate DATE,
	isActive TINYINT NOT NULL DEFAULT 1
)

CREATE TABLE ALBUM(
	albumID INT IDENTITY(1,1) PRIMARY KEY,
	albumName NVARCHAR(200) NOT NULL,
	coverImage NVARCHAR(255),
	releaseDate DATE,
	isActive TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE SONG(
	songID INT IDENTITY(1,1) PRIMARY KEY,
	title NVARCHAR(200) NOT NULL,
	duration INT NOT NULL,
	audioURL NVARCHAR(255) NOT NULL,
	lyric NVARCHAR(MAX),
	releaseDate DATE,
	coverImage NVARCHAR(255),
	isActive TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE SONG_ARTIST(
	songID INT NOT NULL,
	artistID INT NOT NULL,
	CONSTRAINT PK_SongArtist PRIMARY KEY(songID, artistID),
	CONSTRAINT FK_SongArtist_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID),
	CONSTRAINT FK_SongArtist_Artist
	FOREIGN KEY(artistID) REFERENCES ARTIST(artistID)
);
CREATE TABLE ALBUM_ARTIST(
	albumID INT NOT NULL,
	artistID INT NOT NULL,
	CONSTRAINT PK_AlbumArtist PRIMARY KEY (albumID, artistID),
	CONSTRAINT FK_AlbumArtist_Album
	FOREIGN KEY(albumID) REFERENCES ALBUM(albumID),
	CONSTRAINT FK_AlbumArtist_Artist
	FOREIGN KEY(artistID) REFERENCES ARTIST(artistID)
);

CREATE TABLE ALBUM_SONG(
	albumID INT NOT NULL,
	songID INT NOT NULL,
	CONSTRAINT PK_AlbumSong PRIMARY KEY(albumID, songID),
	CONSTRAINT FK_AlbumSong_Album
	FOREIGN KEY(albumID) REFERENCES ALBUM(albumID),
	CONSTRAINT FK_AlbumSong_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE PLAYLIST(
	playListID INT IDENTITY(1,1) PRIMARY KEY,
	playListName VARCHAR(100) NOT NULL,
	userID INT NOT NULL,
	isPublic TINYINT NOT NULL DEFAULT 1,
	createDate DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_PlayList_User
	FOREIGN KEY(userID) REFERENCES USERS(userID)
);

CREATE TABLE PLAYLIST_SONG(
	playListID INT NOT NULL,
	songID INT NOT NULL,
	addDate DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_PlayListSong PRIMARY KEY(playListID, songID),
	CONSTRAINT FK_PlayListSong_PlayList
	FOREIGN KEY(playListID) REFERENCES PLAYLIST(playListID),
	CONSTRAINT FK_PlayListSong_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE FAVORITE_SONG(
	userID INT NOT NULL,
	songID INT NOT NULL,

	CONSTRAINT PK_FavoriteSong PRIMARY KEY(userID, songID),
	CONSTRAINT FK_FavoriteSong_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_FavoriteSong_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE LISTENING_HISTORY(
	userID INT NOT NULL,
	songID INT NOT NULL,
	listenedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_Listening_History PRIMARY KEY(userID, songID, listenedAt),
	CONSTRAINT FK_Listening_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_Listening_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE SONG_SHARE(
	userID INT NOT NULL,
	songID INT NOT NULL,
	shareAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_SongShare PRIMARY KEY(userID, songID, shareAt),
	CONSTRAINT FK_SongShare_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_SongShare_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE ARTIST_FOLLOW(
	userID INT NOT NULL,
	artistID INT NOT NULL,

	CONSTRAINT PK_ArtistFollow PRIMARY KEY(userID, artistID),
	CONSTRAINT FK_ArtistFollow_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_ArtistFollow_Artist
	FOREIGN KEY(artistID) REFERENCES ARTIST(artistID)
);

CREATE TABLE COMMENTS(
	commentID INT IDENTITY(1,1) PRIMARY KEY,
	userID INT NOT NULL,
	songID INT NOT NULL,
	content NVARCHAR(MAX) NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT GETDATE(),
	[status] TINYINT NOT NULL DEFAULT 1,

	CONSTRAINT FK_Comment_User
	FOREIGN KEY(userID) REFERENCES USERS(userID),
	CONSTRAINT FK_Comment_Song
	FOREIGN KEY(songID) REFERENCES SONG(songID)
);

CREATE TABLE DONATION(
	donationID INT IDENTITY(1,1) PRIMARY KEY,
	userID INT NOT NULL,
	amount DECIMAL(10,2) NOT NULL,
	[message] NVARCHAR(255),
	paymentMethod NVARCHAR(50),
	[status] NVARCHAR(20),
	createAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Donation_User
	FOREIGN KEY(userID) REFERENCES USERS(userID)
);

CREATE TABLE NOTIFICATIONS(
	notificationID INT IDENTITY(1,1) PRIMARY KEY,
	userID INT NOT NULL,
	title NVARCHAR(100) NOT NULL,
	content NVARCHAR(255),
	[type] NVARCHAR(50),
	isRead TINYINT NOT NULL DEFAULT 0,
	createAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Notification_User
	FOREIGN KEY(userID) REFERENCES USERS(userID)
);

CREATE TABLE EMAIL_LOG(
	emailLogID INT IDENTITY(1,1) PRIMARY KEY,
	userID INT NOT NULL,
	email NVARCHAR(100) NOT NULL,
	[type] NVARCHAR(50),
	[status] NVARCHAR(20),
	sentAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_EmailLog_User
	FOREIGN KEY(userID) REFERENCES USERS(userID)
);